#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LeftClaw,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightFrontMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           LeftRearMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           LeftFrontMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port5,           RightRearMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port6,           UpperLeftLift, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LowerLeftLift, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           UpperRightLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LowerRightLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RightClaw,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#define RightJoystickY  vexRT[Ch2] //Lets you write LeftJoystickY instead of vexRT[Ch1]
#define RightJoystickX vexRT[Ch1] //Lets you write LeftJoystickX instead of vexRT[Ch2]
#define LeftJoystickX vexRT[Ch4] //Lets you write RightJoystickX instead of vexRT[Ch4]

void LiftControl(int speed)
{
	motor[UpperLeftLift] = speed;
	motor[UpperRightLift] = speed;
	motor[LowerLeftLift] = speed;
	motor[LowerRightLift] = speed;
}
void DriveBackward(int b, int f)
{
	motor[LeftFrontMotor] = b;
	motor[LeftRearMotor] = b;
	motor[RightFrontMotor] = f;
	motor[RightRearMotor] = f;
}
void DriveForward(int x, int y)
{
	motor[LeftFrontMotor] = x;
	motor[LeftRearMotor] = x;
	motor[RightFrontMotor] = y;
	motor[RightRearMotor] = y;
}
void ClawControl(int speed)
{
	motor[LeftClaw] = speed;
	motor[RightClaw] = speed;
}


void DriveRight(int n, int p)
{
	motor[LeftFrontMotor] = n;
	motor[LeftRearMotor] = p;
	motor[RightFrontMotor] = n;
	motor[RightRearMotor] = p;
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{
	//DriveForward(-127, 127);
	//wait1Msec(400);

	//wait1Msec(100);

	//DriveRight(127, -127);
	//wait1Msec(750);

	//wait1Msec(100);

	//DriveForward(-127, 127);
	//wait1Msec(400);

	//wait1Msec(100);

	//DriveRight(-127, 127);
	//wait1Msec(750);

	//wait1Msec(100);

	ClawControl(127);
	LiftControl(127);
	wait1Msec(2000);
	ClawControl(0);
	LiftControl(0);

	wait1Msec(100);

  DriveForward(-127, 127);
  ClawControl(127);
  wait1Msec(1000);
  ClawControl(127);
  DriveForward(0, 0);
//Here the robot drive forward
  //for 4 seconds while simultaneously bring the lift up.

  ClawControl(127);
  wait1Msec(1000);
  ClawControl(0);

  wait1Msec(100);
//This wait statement will give the robot
  //a little rest before completing its next actions.

  DriveBackward(127, -127);
  wait1Msec(2000);
  DriveBackward(0, 0);
  //Here the robot will reverse all of its actions
  //by bringing the lift down and driving back to its starting position.
}

task usercontrol()
{
	while(true)
	{
		//--------------------------Base Control-------------------------//
		// Y component, X component, Rotation
		motor[LeftFrontMotor] = -RightJoystickY - RightJoystickX - LeftJoystickX;
		//The Left Front motor is equal to the negative Y-axis minus the X-axis on the right joystick
		motor[RightRearMotor] =  RightJoystickY + RightJoystickX - LeftJoystickX;
		//The Right Rear motor is equal to the Y-axis plus the X-axis on the right joystick
		motor[LeftRearMotor] = -RightJoystickY + RightJoystickX - LeftJoystickX;
		//The Left Rear motor is equal to the negative Y-axis plus the X-axis on the right joystick
		motor[RightFrontMotor] =  RightJoystickY - RightJoystickX - LeftJoystickX;
		//The Right Front motor is equal to the Y-axis minus the X-axis on the right joystick
		//The LeftJoystickX that is being added onto the end of these lines allows the robot to spin side to side using the Left joystick

		// Motor values can only be updated every 20ms
		wait10Msec(2);
		//-------------------------Base Control-------------------------//

		//-------------------------Claw Control-------------------------//
		if(vexRT[Btn6UXmtr2] == 1 && vexRT[Btn6DXmtr2] == 0)
			{
				motor[LeftClaw] = 127;
				motor[RightClaw] = 127;
			}

		else if(vexRT[Btn6DXmtr2] == 1 && vexRT[Btn6UXmtr2] == 0)
			{
				motor[LeftClaw] = -127;
				motor[RightClaw] = -127;
			}

		else
			{
				motor[LeftClaw] = 0;
				motor[RightClaw] = 0;
			}
			//This lets you control the claw using button
			//6 up and 6 down on the partner controller.
		//-------------------------Claw Control-------------------------//

		//-------------------------Lift Control-------------------------//
		motor[UpperLeftLift] = vexRT[Ch2Xmtr2];
		motor[LowerLeftLift] = vexRT[Ch2Xmtr2];
		motor[UpperRightLift] = vexRT[Ch2Xmtr2]*.85;
		motor[LowerRightLift] = vexRT[Ch2Xmtr2]*.85;
		//The lines apply to the four motors on the collector
		//to the right joystick on the partner controller.
		//-------------------------Lift Control-------------------------//
	}
}
